### ISSUE TITLE
Support linked issue  when using create a branch from the issue feature

### ISSUE THREAD

**Issue by Kieun** [michalvankodev/copy-issue-labels#12]
Gihub has a feature to create a branch from issue, and it is quite useful for the developer to create a branch for that issue and link a branch to the issue.
https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-a-branch-for-an-issue

When I try to leverage `copy-issue-labels` for my project without offering the linking keyword in commit message or pr description, it does not read labels from the linked issue which is done with `Development` menu in the issue screen.

**Comment by michalvankodev** [comment]
I'm not sure if the github has changed its API since I worked on this. But my initial intention was to copy labels from the linked issues. It was however not possible at that time to read the linked issues from the API response.
See: https://docs.github.com/en/rest/issues/issues?apiVersion=2022-11-28#get-an-issue

**Comment by Kieun** [comment]
Thanks for the response. As a workaround, I'm adding the keyword such as `Closes` or `Fixes` to link the original issue in the pull request message to copy labels.

Do you think it would be resolved in some day?

**Comment by michalvankodev** [comment]
:shrug: hopefully,

I think it is very sensible to be able to see linked issues when you query for an issue. I have no idea why GitHub API is still missing this feature. It will also seem very trivial to implement and as we can see, it would be very useful.

**Comment by michalvankodev** [comment]
@Kieun Check if the issue hasn't been resolved by the latest change that leverages GraphQL API to get the list of linked issues

**Comment by Kieun** [comment]
Thanks for the update. Let me check. I'll add the result from this issue thread.

**Comment by Kieun** [comment]
@michalvankodev It works well. Thanks for the support. :)
