### ISSUE TITLE
Feature request: to extract the issue no from title

### ISSUE THREAD

**Issue by microdataxyz** [michalvankodev/copy-issue-labels#8]
This github action did a great job. Since the default title of a pull request is based on commit message, I would like to extract the referred issue no from the pull request title.

@michalvankodev How do you feel about this feature request?

**Comment by michalvankodev** [comment]
@microdataxyz Hi!

Thanks for your appreciation. I'm not against a new feature like this if it's going to cover a common use case. Can you please elaborate more on the use case? I checked the #9 PR and it just tells me that you usually happen to put the issues into the title of the PR.

The goal of this action was to build on top of existing automation within Github itself. When you mention that your PR `closes #issue` in the body, it will automatically close the issue when the PR gets merged. I'm not aware that this will also work within titles.

**Comment by microdataxyz** [comment]
Hi @michalvankodev,

We work on a small open-source project with a small group of people.  We usually put the issue ref comment on the commit message, which will automatically be bought to the GitHub pull request title while creating a pull request. During the merge phase, we would use the squash merge so that the commit history shows the feature/bug issues in a row. It helps us to manage the source of a fix. The feature/bug issue is where we discuss the requirement/project management. The pull request is the place we review the code and include some tech discussion. That's why we would like to copy labels from the ref issue to the pull request. Currently, we copy the auto-generated pull request title to the body to trigger it.

BTW, GitHub keywords work with the title, too. This is [an example](https://github.com/microdataxyz/idnumbers/pull/92) that was before this action. I need to do it manually.

:grin:

**Comment by michalvankodev** [comment]
> You can link a pull request to an issue by using a supported keyword in the pull request's description or in a commit message. 

You include these keywords in a commit message. That's probably why it works with your use case as well.

When I was designing this action I wanted to use the Github API just to fetch linked issues. Unfortunately, the endpoint didn't include linked issues. That's why I had to do the parsing of the messages myself. 

I am willing to accept your PR. I will just leave some comments and there would be some work required from your side due to "how just github actions work".

I'd like you to try out, whether the endpoint is now able to retrieve connected issues and we could probably skip the whole parsing and rely on github itself, while you will be working on it.

**Comment by michalvankodev** [comment]
Ok, I thought that you will have to do some work, but I figured that I will have to do the publishing myself. I just wanted you to experience the github action architecture on your own.

Will you please check the API whether it includes connected issues?

**Comment by microdataxyz** [comment]
The API [here](https://docs.github.com/en/rest/issues/issues?apiVersion=2022-11-28#get-an-issue) doesn't show that we can get the connected issues from the API. I also checked the [issue comment API](https://docs.github.com/en/rest/issues/comments?apiVersion=2022-11-28#get-an-issue-comment). It doesn't have the connected issue payload from the response.  It looks like we still need to parse the body and title by ourselves.

**Comment by michalvankodev** [comment]
@microdataxyz 

I've released a new version `v1.2.0` with the `from-title` parameter. 

Github seems to struggle with the versioning and it doesn't work like `npm` versioning system so you will need to update all your workflows to point to the `v1.2.0` version of the action.

Thank you very much for your contribution!

Please, let me know if everything works out as expected.
